version: '3.7'

services:
  web:
    build: .
    #command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/work
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0