version: '1.0'

services:
  web:
    build: .
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .
    ports:
      - 8000:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0